#!/bin/bash

mkdir temp
cp chrome.manifest temp
cp install.rdf temp
cp icon.png temp
cp -r chrome temp
cp -r components temp
cp -r defaults temp

cd temp

#Substitute variables
while read LINE; do
    if [[ $LINE != [A-Z]* ]]; then
        continue
    fi
    LINE1=`echo $LINE | grep -oE "^[^=]+"`
    LINE2=`echo $LINE | grep -oE "[^=]+$"`
    sed -i '' "s|\$$LINE1|$LINE2|g" `find . -type f -exec grep -Iq . {} \; -and -print`
    eval "$LINE1=\"$LINE2\""
done < "../config.txt"

zip ../$NAME-$VERSION-sm.xpi * -rq

cd ..
rm -rf temp
